### ISSUE TITLE
API for adding/removing push server endpoints

### ISSUE THREAD

**Issue by zaach** [mozilla/picl-server#62]
We can use the node.js push server for testing these new apis.

Each user will have a set of endpoints, each mapped to a channel on a device that is connected and waiting for updates. There should normally be one channel per device, presumably the picl client that is listening for updates. When a client disconnects, it should request to delete the endpoint from the picl-server.

https://github.com/zaach/node-simplepush

**Comment by rfk** [comment]
> When a client disconnects, it should request to delete the endpoint from the picl-server.

Do we need to garbage-collect these if the client fails to delete them explicitly?  Will a simple time-to-live expiry be sufficient in this case?

**Comment by zaach** [comment]
Yes, garbage collection is a good idea. Though we'll have to be careful not to expire them while their channel is still active. 

The protocol doesn't specify an error code that the PushServer should respond with when it receives a notification for a non-existent channel, or else we could use that as a clue to delete the endpoint. cc/ @vmunix

**Comment by rfk** [comment]
Maybe we can send a final signal on the channel as we're about the garbage-collect it, so any still-connected clients will get bumped and re-connect with a new one.  /me needs to have another read through the protocol spec to get a better handle on these details...

**Comment by rfk** [comment]
> When a client disconnects, it should request to delete the endpoint from the picl-server.

Actually, it's not clear to me what "whenever a client disconnects" really entails, and whether it's necessary to delete the stored endpoint at every disconnection.  My read of the SimplePush docs suggests that there should be a single, long-lived notification endpoint for each device.  It might get reset due to some re-synchronisation between PushServer and client, but doesn't need to be torn down.

Is that accurate?  If so, does it mean that the picl client would be deleting and then re-submitting the same endpoint URL over and over again?

**Comment by zaach** [comment]
Ah, good point. The UA will keep those channelIDs around until it explicitly unregisters them, or the server sends it a new UAID and it removes them all. We could have the picl client delete the endpoint while unregistering or when it receives a system message that the UAID has been reset.
